### ISSUE TITLE
How do you run Streusle against a sentence  to get the labels ?

### ISSUE THREAD

**Issue by zanek** [nert-nlp/streusle#89]
How do you run Streusle against a sentence  to get the labels for the Supersenses ? Is there a python file where you can provide it an english sentence and get output ?

There are so many Python scripts and I read through the readme and everything else but dont see that.

**Comment by nschneid** [comment]
This repository has the STREUSLE corpus. An English tagger trained on the corpus can be found at https://github.com/nelson-liu/lexical-semantic-recognition (it is described in [this paper](https://arxiv.org/abs/2004.15008)).
